# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Interest.create([
				{name: 'Lore', description: 'I love a good story. Space, high fantasy, or both, as long as it is amazing.', image_name: 'lore', long_description: 'There is much and more that can be said of my love of lore. Ever since I was a child, my first love has always been to literature and so it would make sense that for many years I aspired to making it a profession. While I may have interrupted my dreams of writing, reading has never been far from my mind.'},
                {name: 'Games', description: 'Videogames, board games, card games. I am an avid lover of all games.', image_name: 'game', long_description: 'I have long since been a gamer. While I do not hold any illusions of becoming a professional gamer, it is still one of my favorite hobbies. My interests include but are not limited to action rpgs, mmorpgs, rts, fighting games, mobas, platformers, and the list is truly massive. Genres criss cross and are constantly evolving and I have  a passion for trying a large variety of games.'},
                {name: 'Programming', description: 'More than a hobby, I find programming to be a form of artistic expression.', image_name: 'prog', long_description: 'Programming at its core is a tool. What makes programming so interesting to me is that it has infinite applications in terms of what it can be used for. It can be both a hammer and a paintbrush at the same time or a ruler and a telescope. It is whatever you need it to be and combines both the rigid logic of math with the absurd creativity of your imagination to create whatever you like.'},
				{name: 'Outlaw', description: 'My son', image_name: 'outlaw', long_description: 'My surrogate son who I adopted September of 2018. To most he is just a cat but to me he truly is like a son and I love him dearly. I named him outlaw because unfortunately, he really does not take orders from anyone including me, much like an outlaw.'},
				{name: 'Cars', description: 'I have been a long time fan of cars', image_name: 'cars', long_description: 'I have been a fan of muscle cars for as long as I can remember. Most of all I must say I truly love the sound that a naturally aspirated v8 engine makes. That being said I love what is happeneing in the world of electric cars and eagerly  look forward to what comes next with them.'},
				{name: 'PC Building', description: 'PC building has been a hobby of mine for a few years now', image_name: 'pc', long_description: 'Ever since high school I wanted to build my own pc. In college I finally had the opportunity and fell in love with working on hardware. Since then I have built two of my own personal gaming rigs and have helped friends construct their own. There is something I truly love about pc building that cannot easily be captrued with words. I imagine it translates well to how a carpenter feels creating a table. Seeing all the pieces laid out, then the final constructed project and knowing that you built it yourself.'}
				])